const KEY='pilarkAdminOverridesV1';
const mediaDefaults=[
  {key:'hero',name:'Hero thumbnail',description:'Homepage hero image',src:'assets/hero-thumbnail.jpg'},
  {key:'company',name:'Company image',description:'Our Company section',src:'assets/company-thumbnail.jpg'},
  {key:'applications',name:'Applications image',description:'Applications feature background',src:'assets/applications-thumbnail.jpg'},
  {key:'vision',name:'Vision & Mission',description:'Popup image',src:'assets/vision-mission.jpg'}
];
const productDefaults=[
['molded-grating','Molded Grating','assets/molded-grating-product.jpg?v=20260829'],['pultruded-grating','Pultruded Grating','assets/pultruded-grating-thumb.jpg'],['bmc-manhole','BMC Manhole Cover','assets/bmc-manhole-cover-thumb.jpg'],['grating-manhole','Grating Manhole Cover','assets/grating-manhole-cover-thumb.jpg'],['cable-tray','FRP Cable Tray','assets/frp-cable-tray-thumb.jpg'],['cable-ladder','FRP Cable Ladder','assets/frp-cable-ladder-thumb.jpg'],['gfrp-profiles','GFRP Profiles','assets/gfrp-profiles-thumb.jpg'],['handrail','GFRP Handrail','assets/gfrp-handrail-thumb.jpg'],['cage-ladder','FRP Cage Ladder','assets/frp-cage-ladder-thumb.jpg'],['gfrp-rebar','GFRP Rebar','assets/gfrp-rebar-thumb.jpg'],['gfrp-wire-mesh','GFRP Wire Mesh','assets/grp-wire-mesh.jpg'],['drainage-bmc','BMC Trench Drainage','assets/bmc-trench-drainage.jpg'],['drainage-pp','Polypropylene Drainage','assets/polypropylene-drainage.jpg'],['polymer-concrete','Polymer Concrete Drainage','assets/polymer-concrete-drainage.jpg'],['individual-septic','Individual Bio Septic Tank','assets/individual-bio-septic-tank.jpg'],['communal-septic','Communal Bio Septic Tank','assets/communal-bio-septic-tank.jpg'],['frp-sheet-piling','FRP Sheet Piling','assets/frp-sheet-piling.jpg'],['gfrp-optic-pole','GFRP Optic Pole','assets/gfrp-optic-pole.jpg']
];
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}}
function save(data){localStorage.setItem(KEY,JSON.stringify(data))}
function getMedia(item){return load().media?.[item.key]||item.src}
function getProduct(id,src){return load().products?.[id]?.img||src}
function upload(file,done){if(!file)return;if(file.size>3500000){alert('For this prototype, please use an image below 3.5 MB. Cloud storage will remove this limitation.');return}const r=new FileReader();r.onload=()=>done(r.result);r.readAsDataURL(file)}
function mediaCard(item,compact=false){return '<article class="media-card"><div class="media-preview"><img src="'+getMedia(item)+'" alt=""></div><div class="media-card-body"><b>'+item.name+'</b><span>'+item.description+'</span><label class="upload-btn">Replace image<input type="file" accept="image/*" data-media="'+item.key+'"></label></div></article>'}
function renderMedia(){document.getElementById('mediaGrid').innerHTML=mediaDefaults.map(x=>mediaCard(x)).join('');document.getElementById('quickMedia').innerHTML=mediaDefaults.map(x=>mediaCard(x,true)).join('');bindUploads()}
function renderProducts(){document.getElementById('productEditor').innerHTML=productDefaults.map(([id,name,src])=>'<article class="product-edit-card"><img src="'+getProduct(id,src)+'" alt=""><div class="product-edit-body"><h3>'+name+'</h3><span>Product thumbnail</span><label class="upload-btn">Replace thumbnail<input type="file" accept="image/*" data-product="'+id+'"></label></div></article>').join('');bindUploads()}
function bindUploads(){document.querySelectorAll('input[data-media]').forEach(input=>input.onchange=e=>upload(e.target.files[0],result=>{const d=load();d.media=d.media||{};d.media[e.target.dataset.media]=result;save(d);renderMedia()}));document.querySelectorAll('input[data-product]').forEach(input=>input.onchange=e=>upload(e.target.files[0],result=>{const d=load();d.products=d.products||{};d.products[e.target.dataset.product]={img:result};save(d);renderProducts()}))}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+name));document.querySelectorAll('.side-link').forEach(b=>b.classList.toggle('active',b.dataset.view===name));document.getElementById('pageTitle').textContent={dashboard:'Website overview',media:'Media Library',products:'Product thumbnails',sections:'Website sections',settings:'Settings'}[name]||'PILARK Admin'}
document.addEventListener('DOMContentLoaded',()=>{renderMedia();renderProducts();document.getElementById('loginForm').addEventListener('submit',e=>{e.preventDefault();document.getElementById('loginView').hidden=true;document.getElementById('adminApp').hidden=false});document.querySelectorAll('.side-link').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>showView(b.dataset.goto));document.getElementById('logoutBtn').onclick=()=>{document.getElementById('adminApp').hidden=true;document.getElementById('loginView').hidden=false};document.getElementById('resetBtn').onclick=()=>{if(confirm('Reset all local prototype changes?')){localStorage.removeItem(KEY);renderMedia();renderProducts();alert('Local changes reset.')}}});