const products=[
{id:'molded-grating',cat:'FRP Grating',title:'Molded Grating',img:'assets/molded-grating-product.jpg?v=20260829',modalImg:'assets/profile/page14.jpg',desc:'GFRP molded grating manufactured through a molding process using fiberglass reinforcement, thermosetting resin and controlled curing.',page:14,features:['Open-mold manufacturing process','Corrosion and chemical resistance','Non-conductive composite flooring','Multiple mesh, color and surface options'],spec:[['Typical application','Industrial flooring, platforms, walkways, trench covers'],['Open area','Multiple configurations in catalog'],['Surface options','Anti-skid, concave, chequered plate, flat'],['Colors','Dark green, dark grey, light grey, yellow']]},
{id:'pultruded-grating',cat:'FRP Grating',title:'Pultruded Grating',img:'assets/pultruded-grating-thumb.jpg',modalImg:'assets/catalog/page19.jpg',desc:'Pultruded grating manufactured by pulling fiberglass reinforcements through resin, then shaping and heating into structural grating profiles.',page:15,features:['High strength-to-weight ratio','Directional load-bearing performance','Lightweight modular construction','Demanding industrial environments'],spec:[['Series','G-2500, G-4000, G-5000'],['Cross rod','Catalog provides dimensions by series'],['Open area','Catalog provides values by series']]},
{id:'bmc-manhole',cat:'Manhole Covers',title:'BMC Manhole Cover',img:'assets/bmc-manhole-cover-thumb.jpg',modalImg:'assets/profile/page15.jpg',desc:'BMC manhole cover system using bulk molding compound for inspection chambers where strength, corrosion resistance and lightweight handling are required.',page:24,features:['Rounded and square variants','Resin and glass-fiber composite','Lightweight','Multiple colors'],spec:[['Material','BMC / Bulk Molding Compound'],['Variants','Rounded and Square'],['Colors','Black, Light Grey, Yellow, Green']]},
{id:'grating-manhole',cat:'Manhole Covers',title:'Grating Manhole Cover',img:'assets/grating-manhole-cover-thumb.jpg',desc:'Combination of molded grating and chequered plate for manhole access, providing strength, slip resistance and drainage/open-area performance.',page:16,features:['Molded grating + chequered plate','Anti-slip performance','Practical access solution','Custom applications supported'],spec:[['Product','Grating Manhole Cover'],['Surface','Chequered plate / molded grating'],['Application','Manholes and inspection areas']]},
{id:'cable-tray',cat:'Cable Management',title:'FRP Cable Tray',img:'assets/profile/page18.jpg',desc:'GFRP cable support system designed to organize cable routes and reduce maintenance in demanding environments.',page:27,features:['Strong GFRP construction','Electrical insulation','Corrosion resistance','Straight and fitting configurations'],spec:[['System','FRP Cable Tray'],['Use','Cable routing and support'],['Fittings','Horizontal elbow, vertical elbow, tee and reducer']]},
{id:'cable-ladder',cat:'Cable Management',title:'FRP Cable Ladder',img:'assets/profile/page19.jpg',desc:'GFRP cable ladder system consisting of two longitudinal side rails connected by cross bars for open, accessible cable support.',page:28,features:['Open structure','Maintenance-friendly','Lightweight and corrosion resistant','Type 100 and Type 150'],spec:[['Types','Type 100, Type 150'],['Load test','Catalog includes load-test tables'],['Standards','NEMA loading standards referenced']]},
{id:'gfrp-profiles',cat:'Structural FRP',title:'GFRP Profiles',img:'assets/profile/page17.jpg',desc:'Pultruded GFRP structural profiles available in cross-sectional shapes for construction and industrial applications.',page:30,features:['Square and rectangular hollow','U-channel','Equal-angle','I-beam, floor deck and C-channel'],spec:[['Manufacturing','Pultrusion'],['Material','GFRP'],['Applications','Structural and construction components']]},
{id:'handrail',cat:'Access & Safety',title:'GFRP Handrail',img:'assets/profile/page22.jpg',desc:'GFRP handrail and fittings providing high strength, corrosion resistance and easy installation.',page:33,features:['Base mounting square','3-way and 4-way corners','Cross joint and adjustable elbow','Modular handrail systems'],spec:[['Material','GFRP'],['Tube','Round tube configurations'],['Applications','Industrial facilities, bridges, platforms, infrastructure']]},
{id:'cage-ladder',cat:'Access & Safety',title:'FRP Cage Ladder',img:'assets/catalog/page35.jpg',desc:'FRP cage ladder system designed for safe, durable access in industrial and commercial facilities.',page:35,features:['Corrosion resistant','Protective cage','Non-conductive','Lightweight'],spec:[['System','FRP Cage Ladder'],['Components','Elliptic bar, U-channel, flat bar and serrated tube'],['Application','Industrial and commercial access']]},
{id:'gfrp-rebar',cat:'GFRP Reinforcement',title:'GFRP Rebar',img:'assets/profile/page23.jpg',desc:'Concrete reinforcement made from fiberglass and resin, offering lower weight and corrosion resistance for structures exposed to harsh environments.',page:37,features:['Lightweight','High tensile strength','Non-corrosive','Aggressive environments'],spec:[['Diameter','6, 8, 10, 12, 16, 22, 28, 32, 36, 38 mm'],['Length','6000 mm'],['Tensile strength','Catalog provides values by diameter'],['Weight','Catalog provides kg/m by diameter']]},
{id:'gfrp-wire-mesh',cat:'GFRP Reinforcement',title:'GFRP Wire Mesh',img:'assets/catalog/page40.jpg',desc:'Fiberglass and resin reinforcing mesh intended for structures frequently exposed to water, chemicals or corrosive environments.',page:40,features:['Corrosion resistant','Lightweight','Non-conductive','Demanding environments'],spec:[['O-Line fiberglass wiremesh','1700 × 2400 × Ø10 mm'],['O-Line fiberglass wiremesh','1700 × 2400 × Ø12 mm']]},
{id:'drainage-bmc',cat:'Drainage',title:'BMC Trench Drainage',img:'assets/catalog/page41.jpg',desc:'BMC trench drainage system formed from thermosetting resin, fiberglass, fillers and additives for durable surface-water management.',page:41,features:['Durable and corrosion resistant','Customizable','Lightweight','Industrial, parking, residential and infrastructure'],spec:[['Material','BMC / thermosetting resin composite'],['System','Trench drainage'],['Catalog data','Width, height, length and weight']]},
{id:'drainage-pp',cat:'Drainage',title:'Polypropylene Drainage',img:'assets/catalog/page42.jpg',desc:'O-Line PP drainage system designed for rapid ground-rainwater collection and directing to municipal pipe networks.',page:42,features:['Polypropylene','Modular channel','Multiple sizes','Connector accessories'],spec:[['Material','Polypropylene'],['Length','1000 mm modules'],['Widths','Multiple dimensions from 100 to 500 mm']]},
{id:'polymer-concrete',cat:'Drainage',title:'Polymer Concrete Drainage',img:'assets/catalog/page43.jpg',desc:'Polymer concrete channels, sumps and kerbs combining mineral fillers with synthetic or natural resin for durable drainage systems.',page:43,features:['Long service life','High-performance composite','Infrastructure and construction','Pits and channels'],spec:[['Material','Polymer concrete'],['Product range','Channels, sumps, kerbs and pits'],['Catalog data','Multiple width/height configurations']]},
{id:'individual-septic',cat:'Septic & Wastewater',title:'Individual Bio Septic Tank',img:'assets/profile/page25.jpg',desc:'Individual septic tank available in GFRP and LLDPE, designed for household wastewater treatment with durable, leak-resistant construction.',page:25,features:['Household wastewater treatment','Strong and lightweight','Leak-resistant','Installation accessories'],spec:[['Materials','GFRP and LLDPE'],['Configuration','Three-chamber system shown'],['Accessories','Sealing tape, sealing ring, nut & screws, elbow pipe, cover, partition panel, honey comb, bio ball']]},
{id:'communal-septic',cat:'Septic & Wastewater',title:'Communal Bio Septic Tank',img:'assets/profile/page26.jpg',desc:'Communal septic tank system designed for wastewater collection and processing from several homes or buildings in one system.',page:26,features:['Communal wastewater treatment','Strong and durable','Corrosion resistant','Multi-house or building applications'],spec:[['Material','GFRP'],['Use','Several homes or buildings'],['Configuration','Horizontal tank with staged treatment']]},
{id:'frp-septic',cat:'Septic & Wastewater',title:'O-Max FRP Septic Tank',img:'assets/catalog/page46.jpg',desc:'FRP septic tank configuration with accessories and assembly/installation guidance shown in the 2026 catalog.',page:46,features:['FRP composite','Three-chamber treatment concept','Accessories','Assembly and installation sequence'],spec:[['Material','FRP'],['Accessories','Sealing tape, sealing ring, nut & screw, elbow pipe, cover, partition panel, honey comb, bio ball']]},
{id:'frp-sheet-piling',cat:'Structural FRP',title:'FRP Sheet Piling',img:'assets/profile/page20.jpg',desc:'FRP sheet piling provides a flexible and lightweight solution for retaining and earth-support applications with corrosion resistance.',page:20,features:['Flexible and lightweight','High section modulus','Corrosion resistant','Retaining and earth support'],spec:[['Material','FRP'],['Application','Retaining, earth support and infrastructure']]},
{id:'gfrp-optic-pole',cat:'Utility',title:'GFRP Optic Pole',img:'assets/profile/page21.jpg',desc:'Composite pole made from fiberglass reinforced resin, designed for outdoor lighting and communication infrastructure.',page:21,features:['Lightweight','High mechanical strength','Corrosion resistant','Outdoor lighting and communication'],spec:[['Material','GFRP'],['Application','Outdoor lighting and communication infrastructure']]}
];
const $=id=>document.getElementById(id);
const categories=['All',...new Set(products.map(p=>p.cat))];
function renderFilters(){const el=$('filters');if(!el)return;el.innerHTML=categories.map((c,i)=>`<button class="filter ${i?'':'active'}" data-filter="${c}">${c}</button>`).join('');el.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{el.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts(b.dataset.filter)})}
function renderProducts(filter='All'){const el=$('productGrid');if(!el)return;const list=filter==='All'?products:products.filter(p=>p.cat===filter);el.innerHTML=list.map(p=>`<article class="product reveal"><div class="product-media"><img loading="lazy" src="${p.img}" alt="${p.title}"></div><div class="product-body"><div class="product-meta"><span class="pill">${p.cat}</span><span class="text-muted">Catalog p.${p.page}</span></div><h3>${p.title}</h3><p>${p.desc}</p><button class="product-link" data-product="${p.id}" style="border:0;background:none;padding:0;cursor:pointer">Explore specifications →</button></div></article>`).join('');el.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>openProduct(b.dataset.product));observeReveals()}
function openProduct(id){const p=products.find(x=>x.id===id),m=$('productModal');if(!p||!m)return;$('modalTitle').textContent=p.title;$('modalImage').src=p.modalImg||p.img;$('modalImage').alt=p.title;$('modalDesc').textContent=p.desc;$('modalFeatures').innerHTML=p.features.map(x=>`<li>${x}</li>`).join('');$('modalSpec').innerHTML=p.spec.map(r=>`<tr><th>${r[0]}</th><td>${r[1]}</td></tr>`).join('');$('modalCatalog').href=`assets/catalog/page${String(p.page).padStart(2,'0')}.jpg`;m.classList.add('open');document.body.classList.add('lock')}
function closeModal(){$('productModal')?.classList.remove('open');document.body.classList.remove('lock')}
let galleryPages=[],galleryIndex=0;
function openLightbox(src,index=0){galleryPages=[...document.querySelectorAll('.catalog-thumb img')].map(x=>x.src);galleryIndex=index;$('lightImg').src=src;$('lightbox').classList.add('open');document.body.classList.add('lock')}
function galleryMove(dir){if(!galleryPages.length)return;galleryIndex=(galleryIndex+dir+galleryPages.length)%galleryPages.length;$('lightImg').src=galleryPages[galleryIndex]}
function closeLight(){$('lightbox').classList.remove('open');document.body.classList.remove('lock')}
function renderCatalog(){const el=$('catalogGrid');if(!el)return;el.innerHTML=Array.from({length:49},(_,i)=>{const n=i+1,s=String(n).padStart(2,'0');return `<div class="catalog-thumb" onclick="openLightbox('assets/catalog/page${s}.jpg',${i})"><img loading="lazy" src="assets/catalog/page${s}.jpg" alt="PILARK Catalog 2026 page ${n}"><span>Catalog 2026 · p.${n}</span></div>`}).join('')}
function observeReveals(){if(!window.IntersectionObserver){document.querySelectorAll('.reveal').forEach(x=>x.classList.add('show'));return}const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');o.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal:not(.show)').forEach(el=>o.observe(el))}
document.addEventListener('DOMContentLoaded',()=>{renderFilters();renderProducts();renderCatalog();observeReveals();$('closeModal')?.addEventListener('click',closeModal);$('productModal')?.addEventListener('click',e=>{if(e.target===e.currentTarget)closeModal()});$('lightClose')?.addEventListener('click',closeLight);$('lightPrev')?.addEventListener('click',()=>galleryMove(-1));$('lightNext')?.addEventListener('click',()=>galleryMove(1));$('lightbox')?.addEventListener('click',e=>{if(e.target===e.currentTarget)closeLight()});const menu=$('mobileMenu'),btn=$('menuBtn');btn?.addEventListener('click',()=>menu?.classList.toggle('open'));menu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>menu.classList.remove('open')));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();closeLight()}})});

document.addEventListener('DOMContentLoaded',()=>{
  const footerLogo= document.querySelector('footer .logo');
  if(footerLogo){footerLogo.innerHTML='<img src="assets/pilark-logo-footer.svg?v=20260828" alt="PILARK Composites" style="height:58px;width:150px;object-fit:contain;object-position:left center">';}
  document.querySelectorAll('a[href^="mailto:"]').forEach(a=>{a.href='mailto:support@pilarkomposit.com';a.textContent='support@pilarkomposit.com';});
});
