const products=[
['01','FRP Grating','Molded Grating','GFRP molded grating manufactured through a molding process using fiberglass reinforcement, thermosetting resin and controlled curing.','FRP Grating','Molded grating systems','Industrial platforms, walkways, drainage, access','Catalog pp. 14–23'],
['02','FRP Grating','Pultruded Grating','Pultruded grating is manufactured by pulling fiberglass reinforcement through resin and forming structural profiles.','FRP Grating','Pultruded structural grating','Platforms, walkways, industrial flooring','Catalog pp. 14–20'],
['03','Manhole Covers','BMC Manhole Cover','BMC stands for Bulk Molding Compound, a composite material based on resin and glass-fiber reinforcement. The catalog describes an 800 mm cover with 60 mm thickness and a maximum load of 25,000 kg.','Manhole Covers','BMC composite','Inspection chambers and access applications','Catalog pp. 24–26'],
['04','Cable Management','FRP Cable Tray','GFRP cable support systems for organizing cable routes and reducing maintenance in demanding environments.','Cable Management','FRP / GFRP','Cable routing in industrial and utility facilities','Catalog pp. 27–29'],
['05','Cable Management','FRP Cable Ladder','Cable ladder systems with side rails and cross bars for accessible cable support. The catalog includes fittings and load-test information.','Cable Management','FRP / GFRP','Power, industrial and utility cable systems','Catalog pp. 27–29'],
['06','Structural FRP','GFRP Profiles','Pultruded structural components including square hollow, rectangular hollow, U-channel, angles, I-beam, floor deck and C-channel.','Structural FRP','Pultruded GFRP','Frames, supports, platforms and structures','Catalog pp. 30–32'],
['07','Access & Safety','GFRP Handrail','FRP handrails and fittings provide a strong, corrosion-resistant, lightweight solution for access platforms, bridges and industrial facilities.','Access & Safety','GFRP pultruded system','Edge protection and access systems','Catalog pp. 33–34'],
['08','Access & Safety','FRP Cage Ladder','FRP cage ladders provide safe and durable access for industrial and commercial facilities, with modular components and installation dimensions.','Access & Safety','FRP / GFRP','Vertical access','Catalog pp. 35–36'],
['09','GFRP Reinforcement','GFRP Rebar','GFRP rebar is a concrete reinforcing bar made from fiberglass and resin, offering lightweight and corrosion-resistant reinforcement.','GFRP Reinforcement','Fiberglass + resin','Concrete reinforcement in aggressive environments','Catalog pp. 37–39'],
['10','GFRP Reinforcement','GFRP Wire Mesh','GFRP wire mesh is a reinforcing mesh made from fiberglass and resin and is lighter than steel.','GFRP Reinforcement','Fiberglass + resin','Concrete and corrosion-exposed reinforcement','Catalog p. 40'],
['11','Drainage','BMC Trench Drainage','BMC trench drainage systems are formed from thermosetting resin, fiberglass, fillers and additives for durable surface-water management.','Drainage','BMC composite','Trenches and surface-water drainage','Catalog p. 41'],
['12','Drainage','O-Line PP Drainage','Polypropylene linear drainage primarily used for rapidly collecting ground rainwater and directing it to municipal pipe networks.','Drainage','Polypropylene','Commercial blocks, parks, parking lots, roads, ports and airports','Catalog p. 42'],
['13','Drainage','O-Line Polymer Concrete Drainage','Polymer concrete channels, sumps and kerbs combine mineral fillers with synthetic or natural resin for durable drainage systems.','Drainage','Polymer concrete','Building, construction, infrastructure and drainage','Catalog p. 43'],
['14','Septic & Wastewater','O-Max PP Septic Tank','Three-chamber septic tanks for staged domestic wastewater treatment. The catalog includes O-Max PP configurations and specifications.','Septic & Wastewater','Polypropylene','Residential, offices, hotels, schools, hospitals and public facilities','Catalog pp. 44–45'],
['15','Septic & Wastewater','O-Max FRP Septic Tank','Three-chamber FRP septic tank configurations described in the 2026 catalog with sizes, weights and user capacities.','Septic & Wastewater','FRP','Domestic wastewater treatment','Catalog pp. 44 & 46'],
['16','Septic & Wastewater','Communal Bio Septic Tank','Communal septic systems for wastewater collection and staged treatment from several homes or buildings in one system.','Septic & Wastewater','Composite wastewater system','Residential communities and shared facilities','Catalog pp. 44–46'],
['17','Structural FRP','FRP Sheet Piling','FRP sheet piling provides a lightweight and corrosion-resistant solution for retaining and earth-support applications.','Structural FRP','FRP composite','Retaining and earth-support applications','Catalog 2026'],
['18','Utility','GFRP Optic Pole','Composite poles made from fiberglass reinforced resin for outdoor lighting and communication infrastructure.','Utility','GFRP composite','Lighting and communication infrastructure','Catalog 2026'],
['19','FRP Grating','Trench Cover Molded Grating','Molded grating trench covers for drainage channels and access applications. The catalog provides square and rectangular mesh dimensions and installation details.','FRP Grating','Molded grating','Trench cover and drainage access','Catalog pp. 22–23'],
['20','Manhole Covers','Grating Manhole Cover','Combination of molded grating and chequered plate for manhole access, combining strength, slip resistance and drainage/open-area performance.','Manhole Covers','Composite grating + plate','Manhole and inspection access','Catalog 2026']
];
const grid=document.getElementById('productGrid');
const filters=document.querySelectorAll('.filter');
const modal=document.getElementById('modal');
const modalContent=document.getElementById('modalContent');
function render(filter='all'){grid.innerHTML=products.filter(p=>filter==='all'||p[1]===filter).map(p=>`<article class="product" data-id="${p[0]}"><div class="num">${p[0]}</div><div class="cat">${p[1]}</div><h3>${p[2]}</h3><p>${p[3]}</p></article>`).join('');document.querySelectorAll('.product').forEach(card=>card.addEventListener('click',()=>openProduct(card.dataset.id)))}
function openProduct(id){const p=products.find(x=>x[0]===id);if(!p)return;modalContent.innerHTML=`<div class="modalcat">${p[1]}</div><h2>${p[2]}</h2><p>${p[3]}</p><div class="specgrid"><div class="spec"><b>Product family</b><span>${p[4]}</span></div><div class="spec"><b>Material / system</b><span>${p[5]}</span></div><div class="spec"><b>Typical applications</b><span>${p[6]}</span></div><div class="spec"><b>Reference</b><span>${p[7]}</span></div></div><p><strong>Technical note:</strong> For exact dimensions, load classes, mechanical properties, accessories and installation details, use the corresponding PILARK Catalog 2026 page as the controlling technical reference.</p><a class="btn primary" href="#contact" onclick="closeProduct()">Request technical data ↗</a>`;modal.classList.add('open');document.body.style.overflow='hidden'}
function closeProduct(){modal.classList.remove('open');document.body.style.overflow=''}
render();
filters.forEach(f=>f.addEventListener('click',()=>{filters.forEach(x=>x.classList.remove('active'));f.classList.add('active');render(f.dataset.filter)}));
document.getElementById('closeModal').addEventListener('click',closeProduct);modal.addEventListener('click',e=>{if(e.target===modal)closeProduct()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeProduct()});
document.getElementById('menu').addEventListener('click',()=>document.querySelector('.links').classList.toggle('mobile'));
