alter table public.accounting_accounts add column if not exists is_group boolean not null default false;
create index if not exists idx_accounting_accounts_parent_active on public.accounting_accounts(parent_id,is_active);
insert into public.accounting_accounts(code,name,account_type,parent_id,is_group,reconcile,is_active,note) values
('1000','Assets','asset_current',null,true,false,true,'Chart of Accounts group'),('1010','Cash & Bank','asset_cash',(select id from public.accounting_accounts where code='1000'),true,false,true,'Chart of Accounts group'),('1020','Receivables','asset_receivable',(select id from public.accounting_accounts where code='1000'),true,false,true,'Chart of Accounts group'),('1030','Inventory','asset_current',(select id from public.accounting_accounts where code='1000'),true,false,true,'Chart of Accounts group'),('1040','Prepayments','asset_prepayments',(select id from public.accounting_accounts where code='1000'),true,false,true,'Chart of Accounts group'),('1050','Fixed Assets','asset_fixed',(select id from public.accounting_accounts where code='1000'),true,false,true,'Chart of Accounts group'),('1060','Taxes Receivable','asset_current',(select id from public.accounting_accounts where code='1000'),true,false,true,'Chart of Accounts group'),('2000','Liabilities','liability_current',null,true,false,true,'Chart of Accounts group'),('2010','Payables','liability_payable',(select id from public.accounting_accounts where code='2000'),true,false,true,'Chart of Accounts group'),('2020','Taxes Payable','liability_current',(select id from public.accounting_accounts where code='2000'),true,false,true,'Chart of Accounts group'),('2030','Accrued Liabilities','liability_current',(select id from public.accounting_accounts where code='2000'),true,false,true,'Chart of Accounts group'),('3000','Equity','equity',null,true,false,true,'Chart of Accounts group'),('4000','Revenue','income',null,true,false,true,'Chart of Accounts group'),('5000','Cost of Revenue','expense_direct_cost',null,true,false,true,'Chart of Accounts group'),('6000','Expenses','expense',null,true,false,true,'Chart of Accounts group') on conflict(code) do nothing;
update public.accounting_accounts a set parent_id=(select id from public.accounting_accounts where code='1010') where a.code in ('1100','1110');
update public.accounting_accounts a set parent_id=(select id from public.accounting_accounts where code='1020') where a.code='1200';
update public.accounting_accounts a set parent_id=(select id from public.accounting_accounts where code='1060') where a.code='1210';
update public.accounting_accounts a set parent_id=(select id from public.accounting_accounts where code='1030') where a.code='1300';
update public.accounting_accounts a set parent_id=(select id from public.accounting_accounts where code='1040') where a.code='1400';
update public.accounting_accounts a set parent_id=(select id from public.accounting_accounts where code='1050') where a.code='1500';
update public.accounting_accounts a set parent_id=(select id from public.accounting_accounts where code='2010') where a.code='2100';
update public.accounting_accounts a set parent_id=(select id from public.accounting_accounts where code='2020') where a.code='2200';
update public.accounting_accounts a set parent_id=(select id from public.accounting_accounts where code='2030') where a.code='2300';
update public.accounting_accounts a set parent_id=(select id from public.accounting_accounts where code='3000') where a.code in ('3100','3200');
update public.accounting_accounts a set parent_id=(select id from public.accounting_accounts where code='4000') where a.code in ('4100','4200');
update public.accounting_accounts a set parent_id=(select id from public.accounting_accounts where code='5000') where a.code='5100';
update public.accounting_accounts a set parent_id=(select id from public.accounting_accounts where code='6000') where a.code in ('6100','6200');